### ISSUE TITLE
xgboost model pmml file only have one tree.

### ISSUE THREAD

**Issue by 52DL** [jpmml/jpmml-sparkml-xgboost#2]
hi vruusmann:
  First of all, thanks for your great job!
  Recently, i'm trying to save pmml style xgboost-on-spark model with this plugin, but i found i can only get **one** tree's description in the pmml file. And the result which loading such file will have worse metrics behavior.
  Am i missing something?
Best wishes!

**Comment by vruusmann** [comment]
> i can only get one tree's description in the pmml file

Must be some side-effect of the `ntreeLimit` configuration option (defaults to `1` when using XGBoost-on-Apache Spark ML?):
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Learner.java#L147-L157

Can you provide a reproducible example of this issue (eg. using the Iris dataset)?

**Comment by 52DL** [comment]
Sorry, it my fault of using wrong param name. Please look at this [issue](https://github.com/dmlc/xgboost/issues/3383).
