### ISSUE TITLE
support for spark 3.x

### ISSUE THREAD

**Issue by lcx517** [jpmml/jpmml-sparkml-xgboost#20]
Hi,
I found jpmml-sparkml-xgboost only support spark 2.x, I'm not sure whether jpmml has already supported xgboost in spark 3.x without importing jpmml-sparkml-xgboost?

I tried to rebuild jpmml-sparkml-xgboost by modifing pom.xml to latest version as below: 
```
                 <dependency>
			<groupId>ml.dmlc</groupId>
			<artifactId>xgboost4j-spark_2.12</artifactId>
			<version>1.5.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.12</artifactId>
			<version>3.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-mllib_2.12</artifactId>
			<version>3.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.jpmml</groupId>
			<artifactId>jpmml-sparkml</artifactId>
			<version>1.7.3</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jpmml</groupId>
			<artifactId>pmml-xgboost</artifactId>
			<version>1.6.3</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jpmml</groupId>
			<artifactId>pmml-evaluator</artifactId>
			<version>1.6.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jpmml</groupId>
			<artifactId>pmml-evaluator-test</artifactId>
			<version>1.4.11</version>
			<scope>test</scope>
		</dependency>
```

And I got errors when I built project:
```
[ERROR] /Users/lcx/Desktop/project/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/XGBoostRegressionModelConverter.java:[28,8]
org.jpmml.sparkml.xgboost.XGBoostRegressionModelConverter is not abstract and does not override abstract method getNativeConfiguration() in org.jpmml.converter.HasNativeConfiguration.

[ERROR] /Users/lcx/Desktop/project/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/XGBoostClassificationModelConverter.java:[33,8]
org.jpmml.sparkml.xgboost.XGBoostClassificationModelConverter is not abstract and does not override abstract method getNativeConfiguration() in org.jpmml.converter.HasNativeConfiguration.
```

**Comment by vruusmann** [comment]
> I found jpmml-sparkml-xgboost only support spark 2.x

I won't be updating the JPMML-SparkML-XGBoost codebase.

Instead, I will modularize the "main" JPMML-SparkML project, and introduce a dedicated `pmml-sparkml-xgboost` module to make sure that everything stays synced/up-to-date (exactly as has happened with the JPMML-SkLearn project).

Also, there will be an official JPMML-SparkML LightGBM integration available then.

> I tried to rebuild jpmml-sparkml-xgboost by modifing pom.xml to latest version as below .. and I got errors when I built project.

The 1.X versions of JPMML-SparkML libraries are not API-wise compatible with the 1.6.X version of JPMML-XGBoost library.

Your options:
1. Combine JPMML-SparkML 2.X with JPMML-XGBoost 1.6(.3).
2. Combine JPMML-SparkML 1.X with JPMML-XGBoost 1.5(.6).

If you can handle dealing with snapshot versions, then go with option 1. If not (ie. want to pull everything from Maven Central repository), then go with option 2.

**Comment by vruusmann** [comment]
Please note that the `master` branch of the JPMML-SparkML project contains a slightgly outdated README file.

See here for the most up-to-date version (Library > Compatibility matrix):
https://github.com/jpmml/jpmml-sparkml/blob/2.0.X/README.md

**Comment by vruusmann** [comment]
> Instead, I will modularize the "main" JPMML-SparkML project, and introduce a dedicated pmml-sparkml-xgboost module.

I will close this issue when the above materializes. Current ETA is about two-three weeks (ie. by the end of March 2022).

@lcx517 Stay subscribed to receive a notification about it.

**Comment by lcx517** [comment]
Thank you for your reply :)

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-sparkml/commit/79cf96ae56a579d4b20411a2105e2986e18abd9e
