### ISSUE TITLE
java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel is not supported

### ISSUE THREAD

**Issue by SmileSouth** [jpmml/jpmml-sparkml-xgboost#7]
I ran codes in spark-yarn online,but got the following error message:
```
Exception in thread "main" java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel is not supported
    at org.jpmml.sparkml.ConverterFactory.newConverter(ConverterFactory.java:53)
    at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:109)
    at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:278)
    at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:274)
    ....
```
Codes  for buliding pmml as follows:
```
 val pipelineModel = pipeline.fit(trainDF)
 val pmmlBytes = new PMMLBuilder(trainDF.schema, pipelineModel).buildByteArray()
```
I used Spark 2.2.0, scala 2.11.8, jpmml-sparkml 1.4.5, xgboost4j-spark 0.72.

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel is not supported

Class `m.d.x.s.s.XGBoostClassificationModel` has not been registered with JPMML-SparkML's converter factory.

The registration is defined in the `sparkml2pmml.properties` file here:
https://github.com/jpmml/jpmml-sparkml-xgboost/blob/master/src/main/resources/META-INF/sparkml2pmml.properties

The registration should happen automatically when the JPMML-SparkML-XGBoost library JAR file is added to Spark application classpath.

> I used Spark 2.2.0, scala 2.11.8, jpmml-sparkml 1.4.5, xgboost4j-spark 0.72.

Do you have JPMML-SparkML-XGBoost library JAR file on your classpath as well?

**Comment by SmileSouth** [comment]
Thank you for your reply!
I know the reason why class ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel does not registered from your source code in jpmml-sparkml-xgboost
.The project jar package contains JPMML-SparkML-XGBoost library JAR file, I don't know what to do.

**Comment by SmileSouth** [comment]
I solved the problem mentioned above,but unfortunately I got another,I looked for the answer from the issues before,but had no idea, xgboost needs libsvm format. 
`java.lang.IllegalArgumentException: Expected string, integral, double or boolean type, got vector type`

**Comment by vruusmann** [comment]
> xgboost needs libsvm format.

No it doesn't.

For example, see my code example below, which operates on a "normal" Apache Spark dataframe:
https://github.com/jpmml/jpmml-sparkml-xgboost#usage

**Comment by SmileSouth** [comment]
Thank you for your patience and help to me, and sorry to trouble you again. I solved the previous problem according to your advice,and my application ran near the end of PMML conversion. Another error occurred, I hope it is the last one.
```
**org.jpmml.sparkml.PMMLBuilder.class**
private byte[] buildByteArray(int size){
		PMML pmml = build();
		ByteArrayOutputStream os = new ByteArrayOutputStream(size);
		try {
			MetroJAXBUtil.marshalPMML(pmml, os);
		} catch(JAXBException je){
			throw new RuntimeException(je);
		}
```
when run `MetroJAXBUtil.marshalPMML(pmml, os)` method, it steps into org.jpmml.model.MetroJAXBUtil class, then catch a exception as follows:
```
Exception in thread "main" java.lang.IllegalStateException: Not a GlassFish Metro runtime
    at org.jpmml.model.MetroJAXBUtil.marshalPMML(MetroJAXBUtil.java:27)                                                                                                     
    at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:283)
    at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:274)
	......
Caused by: java.lang.ClassCastException: com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl cannot be cast to com.sun.xml.bind.v2.runtime.JAXBContextImpl
    at org.jpmml.model.MetroJAXBUtil.marshalPMML(MetroJAXBUtil.java:25)
    ... 19 more
```
the related code:
```
public void marshalPMML(PMML pmml, OutputStream os) throws JAXBException {
		JAXBContextImpl context;
		try {
			context = (JAXBContextImpl)JAXBUtil.getContext();
		} catch(ClassCastException cce){
			throw new IllegalStateException("Not a GlassFish Metro runtime", cce);
		}
```
Maybe it caused by jar package version of  pmml-model, but it did not work after trying several times.  Spark 2.2.0, scala 2.11.8, jpmml-sparkml 1.4.5, xgboost4j-spark 0.72, pmml-model 1.4.5.

**Comment by vruusmann** [comment]
> Caused by: java.lang.ClassCastException: com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl cannot be cast to com.sun.xml.bind.v2.runtime.JAXBContextImpl

What's your JVM version/vendor? For some reason it chooses an `internal` interface/implementation over the standard one.

If you cannot make `MetroJAXBUtil#marshalPMML(PMML, OutputStream)` work, then you may switch back to the regular `JAXBUtil#marshalPMML(PMML, OutputStream)`. The main difference between these two utility methods is PMML/XML indentation style (2 spaces and wrapping long lines vs. tabs and not wrapping long lines):
```Java
PMMLBuilder pmmlBuilder = ...
PMML pmml = pmmlBuilder.build();

JAXBUtil.marshalpPMML(pmml, new PrintStream(System.out))
```

**Comment by SmileSouth** [comment]
I solved it, thank you very much!
